### ISSUE TITLE
request update: babel-jsx.js implementation supports babel 6

### ISSUE THREAD

**Issue by septs** [OpenJSX/babel-plugin-jsx#11]
```
[01:26:22] TypeError: babel.Transformer is not a constructor while parsing file: /home/develop/Projects/BPlayerPlus/src/index.js
    at module.exports (/home/develop/Projects/BPlayerPlus/node_modules/babel-plugin-jsx/lib/babel-jsx.js:17:10)
    at plugin (/home/develop/Projects/BPlayerPlus/node_modules/babel-plugin-jsx/gen.js:7:16)
    at Function.memoisePluginContainer (/home/develop/Projects/BPlayerPlus/node_modules/babel-core/lib/transformation/file/options/option-manager.js:134:13)
    at Function.normalisePlugin (/home/develop/Projects/BPlayerPlus/node_modules/babel-core/lib/transformation/file/options/option-manager.js:168:32)
    at /home/develop/Projects/BPlayerPlus/node_modules/babel-core/lib/transformation/file/options/option-manager.js:208:30
    at Array.map (native)
    at Function.normalisePlugins (/home/develop/Projects/BPlayerPlus/node_modules/babel-core/lib/transformation/file/options/option-manager.js:180:20)
    at OptionManager.mergeOptions (/home/develop/Projects/BPlayerPlus/node_modules/babel-core/lib/transformation/file/options/option-manager.js:300:36)
    at OptionManager.addConfig (/home/develop/Projects/BPlayerPlus/node_modules/babel-core/lib/transformation/file/options/option-manager.js:232:10)
    at OptionManager.findConfigs (/home/develop/Projects/BPlayerPlus/node_modules/babel-core/lib/transformation/file/options/option-manager.js:436:16)
```

see https://github.com/OpenJSX/babel-plugin-jsx/blob/master/lib/babel-jsx.js#L17

**Comment by NekR** [comment]
Hi @septs. I don't really actively develop it right. If I will find to for it -- I will do it. But any PR to fix are welcome.
